import time
import ollama
import pandas as pd
from dataclasses import dataclass
from collections import deque

@dataclass
class Task:
    task_id: int
    model: str
    prompt_tokens: int
    start_time: float = None
    end_time: float = None
    output_tokens: int = 0

def run_llm(prompt, task: Task):
    task.start_time = time.time()
    first = True
    first_token_time = None

    for _ in ollama.generate(model=task.model, prompt=prompt, stream=True):
        if first:
            first_token_time = time.time()
            first = False
        task.output_tokens += 1

    task.end_time = time.time()
    return first_token_time

def scheduler_fcfs(queue):
    results = []
    while queue:
        prompt, task = queue.popleft()
        ft = run_llm(prompt, task)
        results.append((task, ft))
    return results

def main():

    models = ["phi3", "qwen2.5:3b", "mistral", "llama3.1:8b", "gemma:2b"]  # All different: Phi, Qwen, Mistral, Llama, Gemma
    prompts = [
  "Hi",
  "Hello",
  "Hey",
  "Good morning",
  "Good evening",
  "How are you?",
  "What's up?",
  "How's your day going?",
  "Tell me a joke.",
  "Tell me a fun fact.",
  "Give me a random fact.",
  "Recommend a movie.",
  "Recommend a book.",
  "Suggest a podcast.",
  "Suggest music to listen to.",
  "Write a short story.",
  "Write a poem.",
  "Give me a motivational quote.",
  "What should I eat for dinner?",
  "Suggest a healthy breakfast.",
  "Give me a quick workout plan.",
  "Create a to\u2011do list for today.",
  "Plan my day.",
  "Give me productivity tips.",
  "Help me write a professional email.",
  "Help me prepare for a job interview.",
  "Write a short story.",
  "Give me a random fact.",
  "Give a simple explanation of operating systems.",
  "Give a simple explanation of prompt engineering.",
  "Help me stay motivated.",
  "Give a simple explanation of DevOps.",
  "How can I manage time better?",
  "Give a simple explanation of operating systems.",
  "Explain cloud computing simply.",
  "Tell me a joke.",
  "Write a short story.",
  "How can I reduce stress?",
  "Recommend a movie.",
  "What is the best way to improve communication skills?",
  "Recommend a movie.",
  "Best ways to improve memory.",
  "Give me tips to improve communication skills.",
  "Best ways to stay motivated.",
  "What is the best way to save money?",
  "Give me tips to stop procrastinating.",
  "Tell me a joke.",
  "Give me tips to reduce stress.",
  "Give a simple explanation of large language models.",
  "Recommend a movie.",
  "Best ways to save money.",
  "Write a poem.",
  "What is global warming?",
  "How can I learn programming?",
  "Recommend a movie.",
  "Give me tips to stop procrastinating.",
  "Give me tips to improve memory.",
  "How does databases work?",
  "How can I learn AI?",
  "Best ways to reduce stress.",
  "Suggest a podcast.",
  "How can I save money?",
  "Recommend a movie.",
  "What is operating systems?",
  "Give me a motivational quote.",
  "Tell me a fun fact.",
  "Give me tips to start investing.",
  "Give a simple explanation of augmented reality.",
  "Suggest music to listen to.",
  "Recommend a movie.",
  "Give a simple explanation of the internet.",
  "Give me a random fact.",
  "How does APIs work?",
  "Explain climate change simply.",
  "Write a short story.",
  "What is the best way to save money?",
  "How does space travel work?",
  "How can I stay motivated?",
  "Recommend a movie.",
  "What is deep learning?",
  "Give a simple explanation of cryptocurrency.",
  "Help me start a business.",
  "How does electric cars work?",
  "Suggest music to listen to.",
  "Give a simple explanation of the internet.",
  "Give me tips to save money.",
  "How does Bitcoin work?",
  "Best ways to stay motivated.",
  "Tell me about DevOps.",
  "Suggest music to listen to.",
  "Give me tips to improve memory.",
  "Tell me about APIs.",
  "Best ways to stay productive.",
  "Recommend a movie.",
  "What is the best way to build confidence?",
  "How can I sleep better?",
  "How can I stop procrastinating?",
  "Give me tips to build muscle.",
  "Tell me a joke.",
  "Give me a random fact.",
  "Tell me about SQL.",
  "Give a simple explanation of prompt engineering.",
  "Recommend a movie.",
  "Suggest music to listen to.",
  "Write a poem.",
  "Recommend a movie.",
  "Recommend a movie.",
  "Help me sleep better.",
  "Give me tips to manage time better.",
  "Help me build confidence.",
  "Give me tips to stay motivated.",
  "Give me tips to improve memory.",
  "Give me tips to improve communication skills.",
  "How does augmented reality work?",
  "Give me a random fact.",
  "Tell me about large language models.",
  "Give a simple explanation of DNA.",
  "How does neural networks work?",
  "Best ways to save money.",
  "Give me tips to manage time better.",
  "Give me a motivational quote.",
  "Suggest music to listen to.",
  "Explain DevOps simply.",
  "Tell me a fun fact.",
  "Write a short story.",
  "Give a simple explanation of climate change.",
  "What is machine learning?",
  "Explain Kubernetes simply.",
  "Give a simple explanation of augmented reality.",
  "Help me stay productive.",
  "Give a simple explanation of wind energy.",
  "Explain electric cars simply.",
  "Write a poem.",
  "Give a simple explanation of deep learning.",
  "How does operating systems work?",
  "Best ways to build confidence.",
  "Give a simple explanation of space travel.",
  "Give me a random fact.",
  "Best ways to prepare for exams.",
  "Give me tips to prepare for exams.",
  "Write a short story.",
  "Give me a random fact.",
  "How does neural networks work?",
  "Give a simple explanation of augmented reality.",
  "Help me sleep better.",
  "What is the best way to improve communication skills?",
  "How does Python programming work?",
  "Give me a motivational quote.",
  "How does JavaScript work?",
  "Write a poem.",
  "Give me tips to stay productive.",
  "Give me tips to learn AI.",
  "What is the best way to improve memory?",
  "Suggest a podcast.",
  "Help me stay motivated.",
  "Tell me about Docker.",
  "Write a poem.",
  "How does prompt engineering work?",
  "Give a simple explanation of APIs.",
  "Best ways to sleep better.",
  "Tell me a joke.",
  "What is Linux?",
  "What is the solar system?",
  "Write a short story.",
  "Tell me a fun fact.",
  "Tell me a joke.",
  "Give a simple explanation of global warming.",
  "Give me a motivational quote.",
  "Write a short story.",
  "Suggest music to listen to.",
  "Best ways to manage time better.",
  "Give me tips to learn AI.",
  "Tell me about machine learning.",
  "Tell me a joke.",
  "What is the best way to manage time better?",
  "How can I lose weight?",
  "What is the best way to learn AI?",
  "Give me a random fact.",
  "Help me sleep better.",
  "Suggest a podcast.",
  "Tell me about large language models.",
  "What is big data?",
  "Write a short story.",
  "Help me learn AI.",
  "Write a short story.",
  "How does evolution work?",
  "Best ways to improve memory.",
  "How does climate change work?",
  "Tell me about climate change.",
  "Give me a motivational quote.",
  "What is the best way to learn AI?",
  "What is DNA?",
  "Give a simple explanation of Linux.",
  "How can I learn programming?",
  "What is quantum computing?",
  "Give me a motivational quote.",
  "Help me save money.",
  "What is data science?",
  "Best ways to sleep better.",
  "Best ways to start investing.",
  "Give me tips to start investing.",
  "How does large language models work?",
  "Explain electric cars simply.",
  "Recommend a movie.",
  "Suggest music to listen to.",
  "Give me a motivational quote.",
  "Help me improve communication skills.",
  "Recommend a movie.",
  "Explain artificial intelligence simply.",
  "Give me tips to start a business.",
  "Suggest a podcast.",
  "Give me a random fact.",
  "What is big data?",
  "How can I improve memory?",
  "Recommend a book.",
  "Tell me a fun fact.",
  "Give a simple explanation of global warming.",
  "Best ways to lose weight.",
  "Suggest a podcast.",
  "Recommend a movie.",
  "Give me a random fact.",
  "Give me tips to save money.",
  "Best ways to save money.",
  "Tell me a fun fact.",
  "Tell me about photosynthesis.",
  "How does evolution work?",
  "Suggest music to listen to.",
  "Give me a motivational quote.",
  "Give a simple explanation of DNA.",
  "Tell me about data science.",
  "Tell me about augmented reality.",
  "How can I lose weight?",
  "Recommend a book.",
  "What is the best way to manage time better?",
  "Recommend a movie.",
  "How can I learn AI?",
  "Give me tips to prepare for exams.",
  "Help me stay productive.",
  "How can I manage time better?",
  "What is databases?",
  "Best ways to start investing.",
  "Best ways to start investing.",
  "Recommend a movie.",
  "What is the best way to focus better?",
  "What is the best way to reduce stress?",
  "What is the best way to learn AI?",
  "How can I build confidence?",
  "Give a simple explanation of the stock market.",
  "How can I manage time better?",
  "Give me tips to prepare for exams.",
  "Help me start a business.",
  "Help me start investing.",
  "Give me a random fact.",
  "Give me tips to lose weight.",
  "Recommend a book.",
  "Best ways to start a business.",
  "Explain photosynthesis simply.",
  "Recommend a movie.",
  "Help me manage time better.",
  "Suggest music to listen to.",
  "What is Linux?",
  "Suggest music to listen to.",
  "Help me build confidence.",
  "Best ways to build confidence.",
  "Tell me a joke.",
  "What is the best way to improve memory?",
  "Help me build muscle.",
  "Explain Docker simply.",
  "Write a poem.",
  "Tell me a fun fact.",
  "Tell me a fun fact.",
  "Explain blockchain simply.",
  "Tell me about blockchain.",
  "Tell me about quantum computing.",
  "Write a short story.",
  "Give a simple explanation of wind energy.",
  "Suggest music to listen to.",
  "Give me a random fact.",
  "Suggest music to listen to.",
  "Tell me a joke.",
  "How does deep learning work?",
  "What is quantum computing?",
  "Suggest a podcast.",
  "Tell me about the stock market.",
  "How can I manage time better?",
  "Explain wind energy simply.",
  "Help me sleep better.",
  "Suggest a podcast.",
  "Help me manage time better.",
  "Give me tips to start a business.",
  "Write a poem.",
  "What is the best way to save money?",
  "What is the best way to stop procrastinating?",
  "Write a short story.",
  "What is global warming?",
  "What is databases?",
  "Suggest music to listen to.",
  "What is the best way to stay motivated?",
  "How does big data work?",
  "How does Ethereum work?",
  "Recommend a book.",
  "Tell me a fun fact.",
  "Give a simple explanation of operating systems.",
  "Suggest music to listen to.",
  "Best ways to improve memory.",
  "What is big data?",
  "How can I reduce stress?",
  "How can I improve communication skills?",
  "What is the best way to focus better?",
  "Tell me about Docker.",
  "Tell me a fun fact.",
  "Write a poem.",
  "Tell me a joke.",
  "Recommend a movie.",
  "Best ways to prepare for exams.",
  "How can I start a business?",
  "Recommend a book.",
  "How can I improve communication skills?",
  "Best ways to start investing.",
  "Best ways to manage time better.",
  "Tell me about DNA.",
  "Explain solar energy simply.",
  "Write a poem.",
  "Help me focus better.",
  "Write a short story.",
  "How does the solar system work?",
  "Give me a motivational quote.",
  "Explain quantum computing simply.",
  "How does global warming work?",
  "Explain cybersecurity simply.",
  "Explain wind energy simply.",
  "Give me a random fact.",
  "Recommend a movie.",
  "Give me a motivational quote.",
  "Give a simple explanation of blockchain.",
  "Suggest a podcast.",
  "Tell me about photosynthesis.",
  "Write a short story.",
  "Suggest a podcast.",
  "Tell me a fun fact.",
  "Tell me a fun fact.",
  "Help me reduce stress.",
  "Best ways to build muscle.",
  "Best ways to save money.",
  "Explain cryptocurrency simply.",
  "Give a simple explanation of deep learning.",
  "Explain electric cars simply.",
  "Best ways to stop procrastinating.",
  "Tell me about electric cars.",
  "Help me build confidence.",
  "Best ways to stay motivated.",
  "Give me a random fact.",
  "How does big data work?",
  "Write a poem.",
  "Give me tips to start a business.",
  "Give me tips to learn AI.",
  "Help me improve communication skills.",
  "How can I sleep better?",
  "What is climate change?",
  "Write a short story.",
  "What is Docker?",
  "Tell me a fun fact.",
  "What is electric cars?",
  "What is the best way to manage time better?",
  "Give me tips to start a business.",
  "Give me tips to sleep better.",
  "How can I manage time better?",
  "How can I prepare for exams?",
  "Explain evolution simply.",
  "Give me a random fact.",
  "Suggest a podcast.",
  "Give me tips to focus better.",
  "What is the best way to improve communication skills?",
  "Suggest a podcast.",
  "Best ways to learn AI.",
  "Explain Ethereum simply.",
  "Explain augmented reality simply.",
  "Help me save money.",
  "Help me improve communication skills.",
  "What is augmented reality?",
  "Suggest a podcast.",
  "How does the solar system work?",
  "Give a simple explanation of JavaScript.",
  "Recommend a book.",
  "What is Kubernetes?",
  "Give me tips to build muscle.",
  "Help me stay motivated.",
  "Recommend a book.",
  "Recommend a book.",
  "Recommend a movie.",
  "Tell me a fun fact.",
  "Suggest music to listen to.",
  "Give me tips to build muscle.",
  "Give a simple explanation of Python programming.",
  "Give me a motivational quote.",
  "Give a simple explanation of operating systems.",
  "Tell me a fun fact.",
  "Help me stay motivated.",
  "Give a simple explanation of cybersecurity.",
  "Tell me a joke.",
  "How does databases work?",
  "What is the best way to focus better?",
  "Explain climate change simply.",
  "How can I learn AI?",
  "Explain virtual reality simply.",
  "How can I sleep better?",
  "Best ways to lose weight.",
  "Tell me about prompt engineering.",
  "Suggest music to listen to.",
  "How can I stop procrastinating?",
  "Explain machine learning simply.",
  "Explain wind energy simply.",
  "Recommend a book.",
  "Explain Ethereum simply.",
  "How can I learn AI?",
  "How does the internet work?",
  "What is the best way to stay motivated?",
  "Suggest music to listen to.",
  "Recommend a book.",
  "Best ways to learn AI.",
  "Give me a motivational quote.",
  "How does wind energy work?",
  "Help me focus better.",
  "Tell me a fun fact.",
  "Give a simple explanation of blockchain.",
  "Tell me about gravity.",
  "Suggest music to listen to.",
  "Write a short story.",
  "What is electric cars?",
  "What is the best way to save money?",
  "How does big data work?",
  "What is neural networks?",
  "What is the best way to build muscle?",
  "Recommend a book.",
  "Recommend a book.",
  "Give me a motivational quote.",
  "Explain data science simply.",
  "Tell me a joke.",
  "How does photosynthesis work?",
  "Give me a random fact.",
  "Explain quantum computing simply.",
  "Give me tips to focus better.",
  "Give a simple explanation of photosynthesis.",
  "What is cybersecurity?",
  "Write a short story.",
  "Best ways to improve communication skills.",
  "How does Linux work?",
  "Give a simple explanation of blockchain.",
  "Explain SQL simply.",
  "Give a simple explanation of space travel.",
  "What is cryptocurrency?",
  "How can I focus better?",
  "How does Bitcoin work?",
  "Help me stay motivated.",
  "Give a simple explanation of Python programming.",
  "Give me a motivational quote.",
  "Write a short story.",
  "Help me sleep better.",
  "How does quantum computing work?",
  "Suggest music to listen to.",
  "Help me save money.",
  "Tell me a fun fact.",
  "Explain deep learning simply.",
  "Give me tips to build muscle.",
  "Give a simple explanation of blockchain.",
  "What is the best way to stop procrastinating?",
  "Give me a motivational quote.",
  "Explain wind energy simply.",
  "Give me tips to sleep better.",
  "How does cybersecurity work?",
  "Suggest music to listen to.",
  "Give me a random fact.",
  "How does Ethereum work?",
  "Suggest a podcast.",
  "What is Docker?",
  "Help me save money.",
  "Recommend a book.",
  "Help me sleep better.",
  "Give me a motivational quote.",
  "What is the best way to learn AI?",
  "Give me tips to build confidence.",
  "Help me start investing.",
  "Suggest a podcast.",
  "Explain global warming simply.",
  "Explain JavaScript simply.",
  "What is Linux?",
  "Give me tips to focus better.",
  "What is the best way to lose weight?",
  "Give a simple explanation of cloud computing.",
  "Recommend a book.",
  "Tell me about Bitcoin.",
  "Tell me about augmented reality.",
  "Tell me a fun fact.",
  "What is quantum computing?",
  "Give me tips to manage time better.",
  "How can I learn AI?",
  "Tell me a fun fact.",
  "Tell me about DevOps.",
  "How does virtual reality work?",
  "Explain Docker simply.",
  "Best ways to stop procrastinating.",
  "Tell me a joke.",
  "How can I start investing?",
  "Tell me about DNA.",
  "Best ways to sleep better.",
  "Give a simple explanation of the internet.",
  "Recommend a book.",
  "Suggest music to listen to.",
  "How does the stock market work?",
  "Give me tips to start investing.",
  "Best ways to learn AI.",
  "Explain electric cars simply.",
  "Give me a random fact.",
  "Tell me about gravity.",
  "How does databases work?",
  "Tell me a fun fact.",
  "Tell me a fun fact.",
  "What is Linux?",
  "Suggest a podcast.",
  "Tell me about Ethereum.",
  "Give me tips to stay motivated.",
  "Recommend a movie.",
  "Write a poem.",
  "Give a simple explanation of DevOps.",
  "Give a simple explanation of solar energy.",
  "Write a short story.",
  "What is the best way to learn AI?",
  "Give me a motivational quote.",
  "Tell me about global warming.",
  "Write a short story.",
  "Recommend a book.",
  "How does Ethereum work?",
  "How can I reduce stress?",
  "Give me tips to stay productive.",
  "How does the internet work?",
  "Give me a random fact.",
  "Give me tips to learn AI.",
  "Explain black holes simply.",
  "What is the best way to sleep better?",
  "Give me tips to prepare for exams.",
  "Give me tips to learn programming.",
  "Tell me about data science.",
  "Help me learn programming.",
  "Write a poem.",
  "Help me prepare for exams.",
  "Suggest music to listen to.",
  "How does Docker work?",
  "Recommend a movie.",
  "Give me tips to reduce stress.",
  "Explain quantum computing simply.",
  "Suggest music to listen to.",
  "Suggest music to listen to.",
  "How does databases work?",
  "Explain deep learning simply.",
  "Give me a motivational quote.",
  "Explain solar energy simply.",
  "Explain Ethereum simply.",
  "Tell me about Kubernetes.",
  "Give a simple explanation of photosynthesis.",
  "What is the best way to build muscle?",
  "Tell me a joke.",
  "Write a short story.",
  "Explain machine learning simply.",
  "Explain Bitcoin simply.",
  "Tell me about virtual reality.",
  "What is the best way to lose weight?",
  "Best ways to focus better.",
  "Give me tips to learn AI.",
  "Tell me about virtual reality.",
  "Give me a motivational quote.",
  "What is the best way to learn programming?",
  "Tell me a joke.",
  "Explain deep learning simply.",
  "Write a short story.",
  "Give me a random fact.",
  "What is the best way to start investing?",
  "Give me a random fact.",
  "How can I start investing?",
  "How does cloud computing work?",
  "Help me manage time better.",
  "Tell me about cybersecurity.",
  "Write a poem.",
  "Suggest music to listen to.",
  "Explain prompt engineering simply.",
  "Give me tips to stop procrastinating.",
  "Give me a random fact.",
  "What is Python programming?",
  "Give me a motivational quote.",
  "How does Kubernetes work?",
  "Help me stay motivated.",
  "Give me a random fact.",
  "How can I build confidence?",
  "Suggest music to listen to.",
  "Best ways to build muscle.",
  "What is DNA?",
  "Tell me about databases.",
  "Give a simple explanation of DevOps.",
  "Give me a random fact.",
  "Suggest music to listen to.",
  "Help me learn programming.",
  "Tell me about APIs.",
  "Suggest music to listen to.",
  "Recommend a book.",
  "Give me a motivational quote.",
  "How does Docker work?",
  "How does Kubernetes work?",
  "Write a short story.",
  "What is the best way to start investing?",
  "Write a short story.",
  "Best ways to build confidence.",
  "Write a poem.",
  "Give me tips to manage time better.",
  "Write a poem.",
  "How can I start a business?",
  "Tell me a fun fact.",
  "What is electric cars?",
  "Explain the internet simply.",
  "How does JavaScript work?",
  "Give a simple explanation of databases.",
  "Write a poem.",
  "Give me a motivational quote.",
  "How does SQL work?",
  "Give me tips to stop procrastinating.",
  "Tell me a fun fact.",
  "Give a simple explanation of SQL.",
  "Best ways to prepare for exams.",
  "Explain augmented reality simply.",
  "Best ways to stay motivated.",
  "Tell me about SQL.",
  "Write a poem.",
  "Recommend a book.",
  "Recommend a book.",
  "Tell me about the solar system.",
  "Tell me a fun fact.",
  "Give a simple explanation of climate change.",
  "How does cloud computing work?",
  "Tell me a fun fact.",
  "Give me tips to build muscle.",
  "Help me reduce stress.",
  "How does virtual reality work?",
  "Give me tips to learn programming.",
  "How does blockchain work?",
  "Suggest a podcast.",
  "Tell me a fun fact.",
  "Tell me a joke.",
  "What is the best way to improve communication skills?",
  "Give me tips to build confidence.",
  "Tell me about black holes.",
  "Give me a random fact.",
  "Help me sleep better.",
  "What is the best way to learn AI?",
  "How does electric cars work?",
  "How does neural networks work?",
  "What is JavaScript?",
  "Tell me a fun fact.",
  "What is the best way to learn programming?",
  "Suggest music to listen to.",
  "Help me start a business.",
  "Recommend a book.",
  "Write a short story.",
  "Give a simple explanation of photosynthesis.",
  "Give me tips to sleep better.",
  "Explain wind energy simply.",
  "Explain DNA simply.",
  "Suggest music to listen to.",
  "Recommend a book.",
  "Give me a motivational quote.",
  "How does space travel work?",
  "Give a simple explanation of large language models.",
  "Tell me a joke.",
  "Give me a random fact.",
  "Give me a motivational quote.",
  "How can I build confidence?",
  "Tell me a fun fact.",
  "How can I stay productive?",
  "What is the best way to save money?",
  "Help me improve communication skills.",
  "Give a simple explanation of databases.",
  "Help me stay motivated.",
  "Tell me a fun fact.",
  "Best ways to improve communication skills.",
  "Tell me a joke.",
  "What is the best way to save money?",
  "Tell me a joke.",
  "Suggest a podcast.",
  "Best ways to stay productive.",
  "Suggest music to listen to.",
  "Suggest a podcast.",
  "Write a poem.",
  "Explain the internet simply.",
  "Write a poem.",
  "Tell me a fun fact.",
  "Give a simple explanation of large language models.",
  "Help me save money.",
  "Best ways to stay motivated.",
  "Give a simple explanation of data science.",
  "How does virtual reality work?",
  "Explain APIs simply.",
  "Write a short story.",
  "Help me manage time better.",
  "Write a poem.",
  "Give me tips to stay motivated.",
  "Explain DevOps simply.",
  "Suggest a podcast.",
  "What is solar energy?",
  "How does large language models work?",
  "Give me tips to start investing.",
  "Give me tips to start a business.",
  "Give a simple explanation of virtual reality.",
  "How can I sleep better?",
  "What is the best way to stay motivated?",
  "What is the best way to stay motivated?",
  "Suggest music to listen to.",
  "What is big data?",
  "Tell me a fun fact.",
  "Tell me about neural networks.",
  "Suggest a podcast.",
  "Explain global warming simply.",
  "Explain augmented reality simply.",
  "Explain climate change simply.",
  "Help me improve communication skills.",
  "What is the best way to reduce stress?",
  "Suggest a podcast.",
  "Tell me about Bitcoin.",
  "Suggest a podcast.",
  "Best ways to learn programming.",
  "Best ways to learn AI.",
  "Give a simple explanation of the stock market.",
  "Give me tips to stay productive.",
  "Write a short story.",
  "Give me tips to build muscle.",
  "Tell me a fun fact.",
  "Best ways to manage time better.",
  "Tell me about operating systems.",
  "Give me a random fact.",
  "Help me start a business.",
  "Give a simple explanation of quantum computing.",
  "How does wind energy work?",
  "Best ways to start investing.",
  "What is the best way to build muscle?",
  "Recommend a movie.",
  "What is the best way to stay productive?",
  "Tell me about electric cars.",
  "Write a short story.",
  "How can I improve communication skills?",
  "What is the best way to focus better?",
  "How does deep learning work?",
  "Give a simple explanation of deep learning.",
  "Recommend a book.",
  "Suggest music to listen to.",
  "What is the best way to lose weight?",
  "Tell me about global warming.",
  "How can I manage time better?",
  "Help me stay motivated.",
  "Help me save money.",
  "How can I manage time better?",
  "Best ways to save money.",
  "How can I reduce stress?",
  "Tell me a fun fact.",
  "Tell me a fun fact.",
  "Help me learn AI.",
  "Give a simple explanation of databases.",
  "Give me a motivational quote.",
  "How can I start investing?",
  "Give me tips to prepare for exams.",
  "Give a simple explanation of large language models.",
  "How can I sleep better?",
  "What is SQL?",
  "Suggest music to listen to.",
  "How does the internet work?",
  "Write a short story.",
  "How does DNA work?",
  "Tell me a joke.",
  "Write a short story.",
  "How does large language models work?",
  "What is artificial intelligence?",
  "How does big data work?",
  "Recommend a movie.",
  "What is the best way to focus better?",
  "Best ways to stay motivated.",
  "Help me learn AI.",
  "Give me tips to learn AI.",
  "Help me manage time better.",
  "Give a simple explanation of DNA.",
  "Give me tips to improve communication skills.",
  "Help me stay productive.",
  "Tell me a joke.",
  "Tell me about black holes.",
  "Suggest a podcast.",
  "Explain Python programming simply.",
  "Tell me about Bitcoin.",
  "Best ways to improve communication skills.",
  "Help me save money.",
  "What is cybersecurity?",
  "Best ways to reduce stress.",
  "Recommend a book.",
  "How does virtual reality work?",
  "Suggest a podcast.",
  "Tell me a joke.",
  "Give a simple explanation of climate change.",
  "How can I improve memory?",
  "Write a poem.",
  "Best ways to sleep better.",
  "How does SQL work?",
  "Give me tips to start investing.",
  "Write a poem.",
  "Suggest music to listen to.",
  "Suggest a podcast.",
  "Give me a motivational quote.",
  "Give me tips to improve communication skills.",
  "Help me improve communication skills.",
  "Tell me a fun fact.",
  "What is the best way to improve memory?",
  "Give a simple explanation of Ethereum.",
  "Give me tips to save money.",
  "How can I build muscle?",
  "What is databases?",
  "Tell me a fun fact.",
  "Tell me about JavaScript.",
  "Write a short story.",
  "Suggest music to listen to.",
  "What is quantum computing?",
  "Give me tips to manage time better.",
  "Give me a random fact.",
  "Give me a motivational quote.",
  "Best ways to lose weight.",
  "Explain Docker simply.",
  "Explain gravity simply.",
  "Write a poem.",
  "Recommend a book.",
  "What is the best way to start investing?",
  "How can I learn AI?",
  "Recommend a book.",
  "What is climate change?",
  "How can I learn AI?",
  "Tell me a fun fact.",
  "Tell me about Linux.",
  "Give me tips to learn AI.",
  "Best ways to improve communication skills.",
  "How does gravity work?",
  "Recommend a book.",
  "Tell me a fun fact.",
  "Give a simple explanation of DNA.",
  "Suggest a podcast.",
  "How does cryptocurrency work?",
  "Give a simple explanation of cryptocurrency.",
  "Give me tips to manage time better.",
  "Suggest music to listen to.",
  "How does quantum computing work?",
  "Suggest a podcast.",
  "Tell me a fun fact.",
  "Help me learn AI.",
  "Explain databases simply.",
  "How can I manage time better?",
  "Write a poem.",
  "Give me a random fact.",
  "Write a poem.",
  "Write a poem.",
  "How can I focus better?",
  "Tell me about databases.",
  "Give me a random fact.",
  "How can I prepare for exams?",
  "How can I save money?",
  "Give me a random fact.",
  "Help me improve memory.",
  "Tell me about photosynthesis.",
  "Help me improve memory.",
  "Tell me a joke.",
  "Recommend a movie.",
  "Tell me a joke.",
  "How can I learn programming?",
  "Explain APIs simply.",
  "Write a poem.",
  "Tell me a joke.",
  "Best ways to manage time better.",
  "How can I improve memory?",
  "Suggest music to listen to.",
  "What is APIs?",
  "How can I focus better?",
  "Suggest a podcast.",
  "Best ways to focus better.",
  "Help me prepare for exams.",
  "Give me a motivational quote.",
  "Write a short story.",
  "Suggest a podcast.",
  "Help me sleep better.",
  "What is the best way to lose weight?",
  "Recommend a book.",
  "Give a simple explanation of wind energy.",
  "What is cloud computing?",
  "Best ways to stay motivated.",
  "Explain APIs simply.",
  "Give a simple explanation of virtual reality.",
  "Tell me about neural networks.",
  "Best ways to start a business.",
  "Recommend a book.",
  "Give me a motivational quote.",
  "How can I focus better?",
  "Recommend a movie.",
  "How can I sleep better?",
  "Help me sleep better.",
  "Write a poem.",
  "Tell me a fun fact.",
  "Recommend a book.",
  "How can I build confidence?",
  "Give me tips to stay productive.",
  "Tell me about databases.",
  "Write a poem.",
  "Best ways to manage time better.",
  "Recommend a book.",
  "Help me build muscle.",
  "Suggest music to listen to.",
  "How can I improve memory?",
  "Tell me about solar energy.",
  "Help me start a business.",
  "Recommend a movie.",
  "Give me a motivational quote.",
  "Recommend a movie.",
  "Suggest music to listen to.",
  "Give me tips to save money.",
  "Help me manage time better.",
  "Tell me a joke.",
  "Write a poem.",
  "Recommend a book.",
  "How does databases work?",
  "What is Kubernetes?",
  "Recommend a book.",
  "Give me a random fact.",
  "Give me tips to start investing.",
  "Give me tips to reduce stress.",
  "How can I stop procrastinating?",
  "Suggest music to listen to.",
  "Explain operating systems simply.",
  "Give a simple explanation of deep learning.",
  "Recommend a book.",
  "What is the best way to learn AI?",
  "Give a simple explanation of the internet.",
  "Give a simple explanation of artificial intelligence.",
  "What is gravity?",
  "Tell me a fun fact.",
  "How can I sleep better?",
  "What is the best way to lose weight?",
  "Best ways to prepare for exams.",
  "Explain Kubernetes simply.",
  "Write a poem.",
  "Tell me about black holes.",
  "What is the best way to sleep better?",
  "How can I build confidence?",
  "Tell me about blockchain.",
  "Tell me a joke.",
  "Write a short story.",
  "Help me learn AI.",
  "Tell me a joke.",
  "Best ways to stop procrastinating.",
  "Suggest music to listen to.",
  "Tell me about augmented reality.",
  "Explain evolution simply.",
  "Explain cybersecurity simply.",
  "Suggest music to listen to.",
  "Suggest a podcast.",
  "Explain deep learning simply.",
  "How can I stop procrastinating?",
  "Explain databases simply.",
  "Give me tips to lose weight.",
  "Give me tips to reduce stress.",
  "How does operating systems work?",
  "Tell me about gravity.",
  "Help me start a business.",
  "What is the best way to focus better?",
  "Help me build muscle.",
  "Write a short story.",
  "How does Kubernetes work?",
  "Give a simple explanation of machine learning.",
  "Suggest music to listen to.",
  "Best ways to improve communication skills.",
  "What is operating systems?",
  "Best ways to focus better.",
  "Tell me about the internet.",
  "Give me a motivational quote.",
  "How can I sleep better?",
  "Help me improve memory.",
  "Best ways to reduce stress.",
  "Give me tips to sleep better.",
  "What is the best way to save money?",
  "What is gravity?",
  "Give me tips to learn AI.",
  "Tell me a joke.",
  "Write a poem.",
  "Recommend a movie.",
  "How does quantum computing work?",
  "Explain machine learning simply.",
  "Best ways to build confidence.",
  "Help me learn AI.",
  "Help me save money.",
  "How can I sleep better?",
  "How can I sleep better?",
  "How can I save money?",
  "How does big data work?",
  "Give a simple explanation of big data.",
  "How does the solar system work?"
]

    # Process each model separately and save to individual CSV files
    for model in models:
        print(f"\nProcessing model: {model}")
        queue = deque()
        rows = []
        
        for i, prompt in enumerate(prompts):
            prompt_tokens = len(prompt.split())  # token proxy
            queue.append((prompt, Task(i, model, prompt_tokens)))
        
        global_start = time.time()

        completed = scheduler_fcfs(queue)

        for task, ft in completed:
            # Calculate TTFT (Time To First Token)
            ttft = ft - task.start_time if ft else 0.0
            
            rows.append({
                "model": task.model,
                "task_id": task.task_id,
                "prompt_tokens": task.prompt_tokens,
                "start_sec": task.start_time - global_start,
                "end_sec": task.end_time - global_start,
                "execution_time_sec": task.end_time - task.start_time,
                "output_tokens": task.output_tokens,
                "ttft": ttft,
                "tokens_per_sec": task.output_tokens / (task.end_time - ft) if ft else 0.0
            })

        # Save results for this model to a separate CSV file
        model_name = model.replace(":", "_").replace(".", "_")
        output_file = f"main_llm_{model_name}.csv"
        pd.DataFrame(rows).to_csv(output_file, index=False)
        print(f"Saved results to {output_file}")

if __name__ == "__main__":
    main()
